name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare public directory
        run: |
          # Create a public directory and copy the static files we want to publish
          rm -rf public || true
          mkdir public
          cp -r *.html js README.md public/ || true
          # Include any additional assets if present
          if [ -d "css" ]; then cp -r css public/; fi
          if [ -d "images" ]; then cp -r images public/; fi

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://$GITHUB_REPOSITORY_OWNER.github.io/${{ github.event.repository.name }}/

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
